version: "3.7"
services:
  # redis
  redis:
    image: redis:6.2.7
    container_name: redis
    ports:
      - 6379:6379
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"
  # mysql
  mysql:
    image: mysql:5.7.39
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"
  znj:
    image: smally84/znj:0.0.1
    container_name: znj
    ports:
      - 9000:9000
    # 自定义配置文件
    # volumes:
    #  - ./etc/znj.yaml:/etc/znj.yaml
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"
